### ISSUE TITLE
Bug when using the plugin with react-router 

### ISSUE THREAD

**Issue by emirdeliz** [natrim/esbuild-plugin-inline-image#2]
I have a URL like this (using react-router): 

`http://localhost:3110/dash/configuration` 

and import an image like this:

`import configurationApresentation from '../../../public/images/diagrama2023.png';`

After the plugin runs I have the following result in the browser:

<img width="524" alt="image" src="https://github.com/natrim/esbuild-plugin-inline-image/assets/6270495/ab33728c-b3a3-48c1-b003-a140de4e47c9">

However, the correct path should be this:

<img width="516" alt="image" src="https://github.com/natrim/esbuild-plugin-inline-image/assets/6270495/5bd3e008-c100-43d0-9c54-1b2fb82627dd">

The problem occurs when the image tries to access the url ./ which in practice is http://localhost:3110/dash/configuration/diagrama2023-OBYODQFU.png. 

However, the correct URL is http://localhost:3110/diagrama2023-OBYODQFU.png

How to fix this?

**Comment by natrim** [comment]
this plugin does not change any paths, it only inlines image if smaller than defined size
(inline means it puts it together with the js code as dataurl (ie. same as css inlined images))
it does nothing to the images otherwise
